export default {
  form: {
    width: 'max-content',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-evenly',
    alignItems: 'baseline',
  },
  label: {
    fontSize: '16px',
    fontFamily: 'sans-serif',
    fontWeight: '600',
    color: '#222',
    padding: '0 0.2em',
    textAlign: 'center',
  },
  select: {
    display: 'inline-block',
    fontSize: '16px',
    fontFamily: 'sans-serif',
    fontWeight: '700',
    color: '#222',
    lineHeight: '1.3',
    padding: '.3em .6em .2em .6em',
    width: 'auto',
    maxWidth: '100%',
    boxSizing: 'border-box',
    margin: '0.2em 0.2em 0.1em 0',
    border: '1px solid #aaa',
    boxShadow: '1px 3px 8px rgba(0,0,0,0.5)',
    borderRadius: '0.3em',
    MozAppearance: 'none',
    WebkitAppearance: 'none',
    appearance: 'none',
    backgroundColor: '#fff',
    backgroundImage: 'linear-gradient(to bottom, #ffffff 0%,#e1e1e1 100%)',
  },
};
